Repository maxGraph/maxGraph, pull requests merged in 2022-11, with the labels that each got.

#128 docs: set the minimum TypeScript requirement to 3.8
  .github/workflows/build.yml
  README.md
  packages/ts-example/package.json
  packages/ts-support/.npmrc
  packages/ts-support/README.md
  packages/ts-support/package.json
  packages/ts-support/src/index.ts
  packages/ts-support/tsconfig.json
Labels: documentation

#120 Fix edge segment handles not being rendered
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/mixins/CellsMixin.ts
Labels: bug

#139 chore(deps): bump typescript from 4.8.3 to 4.9.3
  package.json
Labels: dependencies

#142 docs: configure the auto-generated release notes
  .github/release.yml
Labels: documentation

#127 fix: TouchEvent is not available in Safari and Firefox Desktop
  packages/core/src/view/event/InternalMouseEvent.ts
Labels: bug

#144 docs: include License and Readme files in the npm package
  README.md
  packages/core/LICENSE
  packages/core/README.md
Labels: documentation

#146 docs: update Changelog for version 0.1.0
  CHANGELOG.md
Labels: documentation

#145 docs: update README after the first public release
  README.md
Labels: documentation
