Repository maxGraph/maxGraph, pull requests merged in 2023-12, with the labels that each got.

#266 chore!: only include ESM in the npm package
  .github/workflows/build.yml
  babel.config.js
  package.json
  packages/core/package.json
  packages/core/tsconfig.json
  packages/core/webpack.config.js
  webpack.config.js
Labels: chore

#274 docs: remove extra "markdown-page" page
  packages/website/src/pages/markdown-page.md
Labels: documentation

#280 ci: update modified files that trigger workflow execution
  .github/workflows/build.yml
  .github/workflows/generate-website.yml
Labels: chore

#265 feat(types): improve partial-autocomplete and type inference
  packages/core/src/types.ts
  packages/core/src/view/mixins/EdgeMixin.ts
Labels: enhancement

#272 fix(robustness): prevent errors when a plugin is not loaded
  packages/core/__tests__/view/mixins/ConnectionsMixin.test.ts
  packages/core/__tests__/view/mixins/EdgeMixin.test.ts
  packages/core/__tests__/view/mixins/PanningMixin.test.ts
  packages/core/__tests__/view/mixins/TooltipMixin.test.ts
  packages/core/__tests__/view/mixins/VertexMixin.test.ts
  packages/core/__tests__/view/mixins/utils.ts
  packages/core/jest.config.cjs
  packages/core/src/editor/Editor.ts
  packages/core/src/util/Constants.ts
  packages/core/src/view/Graph.ts
  packages/core/src/view/GraphView.ts
  packages/core/src/view/cell/CellRenderer.ts
  packages/core/src/view/handler/CellEditorHandler.ts
  packages/core/src/view/handler/ConnectionHandler.ts
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/handler/KeyHandler.ts
  packages/core/src/view/handler/PopupMenuHandler.ts
  packages/core/src/view/handler/SelectionHandler.ts
  packages/core/src/view/handler/VertexHandler.ts
  packages/core/src/view/mixins/ConnectionsMixin.ts
  packages/core/src/view/mixins/EditingMixin.ts
  packages/core/src/view/mixins/EventsMixin.ts
  packages/core/src/view/mixins/PanningMixin.ts
  packages/core/src/view/mixins/TooltipMixin.ts
  packages/core/src/view/other/DragSource.ts
  packages/core/src/view/other/Guide.ts
Labels: bug

#284 test: execute tests serially to speed up test execution
  packages/core/package.json
Labels: chore

#287 docs: improve JSDoc of codec classes
  packages/core/src/serialization/Codec.ts
  packages/core/src/serialization/CodecRegistry.ts
  packages/core/src/serialization/ObjectCodec.ts
Labels: documentation

#285 docs(release): improve the "examples repository update" paragraph
  packages/website/docs/development/release.md
Labels: documentation

#288 test: refactor graph initialization
  packages/core/__tests__/serialization/serialization.xml.test.ts
  packages/core/__tests__/utils.ts
  packages/core/__tests__/view/mixins/ConnectionsMixin.test.ts
  packages/core/__tests__/view/mixins/EdgeMixin.test.ts
  packages/core/__tests__/view/mixins/PanningMixin.test.ts
  packages/core/__tests__/view/mixins/TooltipMixin.test.ts
  packages/core/__tests__/view/mixins/VertexMixin.test.ts
Labels: chore

#286 fix: correcly call 'isEdge' in CellEditorHandler
  packages/core/src/view/handler/CellEditorHandler.ts
Labels: bug

#292 docs: improve the getting started documentation
  README.md
  packages/core/README.md
Labels: documentation

#150 feat: restore remaining non-"Editor" examples to Storybook
  packages/core/src/gui/MaxPopupMenu.ts
  packages/core/src/view/Graph.ts
  packages/core/src/view/animate/Morphing.ts
  packages/html/stories/GraphLayout.stories.js
  packages/html/stories/HtmlLabel.stories.js
  packages/html/stories/MenuStyle.stories.js
  packages/html/stories/Scrollbars.stories.js
  packages/html/stories/ShowRegion.stories.js
  packages/html/stories/Wires.stories.js
  packages/html/stories/stashed/GraphLayout.js
  packages/html/stories/stashed/HtmlLabel.js
  packages/html/stories/stashed/MenuStyle.js
  packages/html/stories/stashed/Scrollbars.js
  packages/html/stories/stashed/ShowRegion.js
  packages/html/stories/stashed/Wires.js
  packages/html/stories/stashed/api/hello.js
Labels: enhancement

#298 ci: upload test coverage results
  .github/workflows/build.yml
  .gitignore
  packages/core/jest.config.cjs
Labels: chore
