Repository maxGraph/maxGraph, pull requests merged in 2023-09, with the labels that each got.

#233 fix: allow `HierarchicalLayout` to manage circular dependencies
  packages/core/__tests__/view/layout/HierarchicalLayout.test.ts
  packages/core/src/view/layout/datatypes/GraphHierarchyNode.ts
Labels: bug

#241 fix: use configurable path for `errorImage`
  packages/core/src/util/Utils.ts
Labels: bug

#242 docs: describe the security policy
  SECURITY.md
Labels: documentation

#244 chore: ensure private status is correctly set in package.json files
  package.json
  packages/core/package.json
  packages/html/package.json
  packages/ts-example/package.json
  packages/ts-support/package.json
Labels: chore
