Repository maxGraph/maxGraph, pull requests merged in 2024-11, with the labels that each got.

#553 fix: make ShowRegion story correctly create the preview page
  packages/html/stories/ShowRegion.stories.ts
  packages/website/docs/usage/migrate-from-mxgraph.md
Labels: bug

#554 fix: improve type of the handler parameter in `factoryMethod`
  packages/core/src/gui/MaxPopupMenu.ts
  packages/core/src/gui/MaxToolbar.ts
  packages/html/stories/MenuStyle.stories.ts
  packages/html/stories/ShowRegion.stories.ts
Labels: bug

#555 fix: allow to insert vertex without setting position and size
  packages/core/__tests__/view/mixins/VertexMixin.test.ts
  packages/core/src/types.ts
  packages/core/src/view/geometry/Rectangle.ts
  packages/core/src/view/mixins/VertexMixin.ts
  packages/core/src/view/mixins/VertexMixin.type.ts
Labels: bug

#557 docs: provide more information about global configuration
  packages/core/src/view/plugins/index.ts
  packages/website/docs/usage/global-configuration.md
  packages/website/docs/usage/migrate-from-mxgraph.md
Labels: documentation

#556 docs: improve the "migrate from mxGraph" guide
  packages/website/docs/intro.md
  packages/website/docs/usage/migrate-from-mxgraph.md
Labels: documentation

#561 docs: explain what is included in the changelog file
  CHANGELOG.md
Labels: documentation

#559 chore(deps-dev): bump docusaurus from 3.5.2 to 3.6.0
  package-lock.json
  packages/website/docusaurus.config.ts
  packages/website/package.json
Labels: chore

#560 chore: build with node 20
  .nvmrc
  packages/website/package.json
Labels: chore

#568 docs: improve JSDoc of elements in the `constants` namespace
  packages/core/src/util/Constants.ts
Labels: documentation

#563 feat: allow usage of functions in `CellStateStyle.edgeStyle`
  packages/core/__tests__/serialization/serialization.xml.test.ts
  packages/core/src/types.ts
  packages/core/src/view/style/EdgeStyle.ts
  packages/html/stories/Folding.stories.ts
  packages/html/stories/HelloPort.stories.ts
  packages/html/stories/Monitor.stories.ts
  packages/html/stories/UserObject.stories.ts
Labels: enhancement

#569 feat: ease configuration of handles in `VertexHandler`
  packages/core/src/index.ts
  packages/core/src/util/Constants.ts
  packages/core/src/view/cell/VertexHandle.ts
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/handler/ElbowEdgeHandler.ts
  packages/core/src/view/handler/VertexHandler.ts
  packages/core/src/view/handler/config.ts
  packages/html/.storybook/preview.ts
  packages/html/stories/MenuStyle.stories.ts
  packages/html/stories/ShowRegion.stories.ts
  packages/html/stories/Stencils.stories.ts
  packages/website/docs/usage/global-configuration.md
  packages/website/docs/usage/migrate-from-mxgraph.md
Labels: enhancement

#570 fix: correctly use the default value of `CellStateStyle.editable`
  packages/core/__tests__/view/mixins/EditingMixin.test.ts
  packages/core/src/types.ts
  packages/core/src/view/mixins/EditingMixin.ts
Labels: bug

#573 chore(deps-dev): bump vite from 5.3.6 to 5.4.11
  package-lock.json
  packages/html/package.json
  packages/ts-example-without-defaults/package.json
  packages/ts-example/package.json
Labels: skip-changelog

#575 docs: improve JSDoc of handlers and constants
  packages/core/src/util/Constants.ts
  packages/core/src/view/handler/ConnectionHandler.ts
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/handler/ElbowEdgeHandler.ts
Labels: documentation

#577 feat: let configure the defaults value of the shadow styles
  packages/core/src/index.ts
  packages/core/src/util/Constants.ts
  packages/core/src/util/config.ts
  packages/core/src/view/canvas/AbstractCanvas2D.ts
  packages/core/src/view/canvas/SvgCanvas2D.ts
  packages/core/src/view/canvas/XmlCanvas2D.ts
  packages/core/src/view/geometry/Shape.ts
  packages/html/.storybook/preview.ts
  packages/html/stories/CustomStyleDefaults.stories.ts
  packages/html/stories/FixedIcons.stories.js
  packages/html/stories/Folding.stories.ts
  packages/html/stories/Merge.stories.ts
  packages/html/stories/Monitor.stories.ts
  packages/html/stories/OrgChart.stories.js
  packages/html/stories/Stencils.stories.ts
  packages/html/stories/Wires.stories.js
  packages/website/docs/usage/global-configuration.md
Labels: enhancement

#578 refactor: use constants.NS_SVG instead of hard coded values
  packages/core/src/Client.ts
  packages/core/src/view/GraphView.ts
  packages/core/src/view/geometry/Shape.ts
  packages/core/src/view/image/ImageBundle.ts
Labels: refactor

#567 fix(label): improve editing position and 'label changed" event
  packages/core/src/view/handler/CellEditorHandler.ts
Labels: bug

#576 feat: ease configuration of handles in `EdgeHandler`
  packages/core/src/util/Constants.ts
  packages/core/src/util/config.ts
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/handler/VertexHandler.ts
  packages/core/src/view/handler/config.ts
  packages/html/.storybook/preview.ts
  packages/html/package.json
  packages/html/stories/CustomHandlesConfiguration.stories.ts
  packages/ts-example-without-defaults/vite.config.js
  packages/ts-example/vite.config.js
  packages/website/docs/usage/global-configuration.md
Labels: enhancement

#582 refactor: simplify the reset config functions
  packages/core/__tests__/util/config.test.ts
  packages/core/__tests__/view/handler/config.test.ts
  packages/core/src/util/cloneUtils.ts
  packages/core/src/util/config.ts
  packages/core/src/view/handler/config.ts
Labels: refactor

#585 docs: mention examples in the documentation introduction
  packages/website/docs/intro.md
Labels: documentation

#586 feat: allow the use of circles for edge handles
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/handler/config.ts
  packages/html/stories/CustomHandlesConfiguration.stories.ts
Labels: enhancement
