Repository maxGraph/maxGraph, pull requests merged in 2024-12, with the labels that each got.

#592 fix: correct rotation handle positioning during vertex rotation
  packages/core/src/view/handler/VertexHandler.ts
Labels: bug

#601 chore(deps-dev): bump docusaurus from 3.6.2 to 3.6.3
  package-lock.json
  packages/website/package.json
Labels: dependencies, skip-changelog

#602 docs: add a page to highlight demo and examples
  README.md
  packages/website/docs/demo-and-examples.md
  packages/website/docs/development/_category_.json
  packages/website/docs/known-issues.md
  packages/website/docs/manual/_category_.json
  packages/website/docs/usage/_category_.json
Labels: documentation

#603 docs: add links to specific examples and demos in various pages
  packages/website/docs/usage/css-and-images.md
  packages/website/docs/usage/perimeters.md
Labels: documentation

#598 docs: add content to getting started page
  README.md
  packages/website/docs/intro.md
  packages/website/docs/manual/assets/getting-started/first-graph.gif
  packages/website/docs/manual/assets/getting-started/vertex-style.png
  packages/website/docs/manual/getting-started.md
  packages/website/docs/manual/getting-started.mdx
Labels: documentation

#606 docs: fix link to getting-started page
  packages/website/docs/demo-and-examples.md
Labels: documentation

#524 docs: add a Codecs page
  packages/core/src/serialization/Codec.ts
  packages/website/docs/usage/codecs.md
  packages/website/docs/usage/css-and-images.md
  packages/website/docs/usage/global-configuration.md
  packages/website/docs/usage/migrate-from-mxgraph.md
  packages/website/docs/usage/perimeters.md
  packages/website/docs/usage/plugins.md
  packages/website/old-mxgraph/tutorial.html
Labels: documentation

#607 fix(VertexHandler): do not create label handle for swimlane
  packages/core/src/view/handler/VertexHandler.ts
Labels: bug

#608 chore(deps-dev): bump typescript from 5.6.2 to 5.7.2
  package-lock.json
  package.json
  packages/core/package.json
Labels: dependencies, skip-changelog, javascript
