Repository maxGraph/maxGraph, pull requests merged in 2024-04, with the labels that each got.

#379 fix: declare regular enums instead of const enums
  .eslintrc.json
  packages/core/src/util/Constants.ts
  packages/core/tsconfig.json
Labels: bug

#380 fix: correctly update style when calling Graph methods
  packages/core/__tests__/util/styleUtils.test.ts
  packages/core/__tests__/view/mixins/CellMixin.test.ts
  packages/core/__tests__/view/mixins/EdgeMixin.test.ts
  packages/core/src/util/styleUtils.ts
  packages/core/src/view/GraphDataModel.ts
  packages/core/src/view/cell/Cell.ts
  packages/core/src/view/mixins/CellsMixin.ts
Labels: bug

#384 ci: build with macos-14
  .github/workflows/build.yml
Labels: chore

#386 docs: add issue templates
  .github/ISSUE_TEMPLATE/01-bug-report.md
  .github/ISSUE_TEMPLATE/02-feature-request.md
  .github/ISSUE_TEMPLATE/03-technical-request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#388 docs(dev): better explain issue templates configuration
  .github/ISSUE_TEMPLATE/README.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#387 docs: improve the Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: documentation

#389 refactor: GraphDataModel.isLayer signature accepts `null` Cell
  packages/core/__tests__/GraphDataModel.test.ts
  packages/core/src/view/GraphDataModel.ts
  packages/core/src/view/mixins/SwimlaneMixin.ts
Labels: refactor

#383 fix: correctly compute the style when setting undefined/none
  packages/core/__tests__/view/style/StyleSheet.test.ts
  packages/core/src/view/style/Stylesheet.ts
Labels: bug

#385 fix: correctly manage default `style.foldable` value
  packages/core/src/view/mixins/FoldingMixin.ts
  packages/html/stories/Collapse.stories.js
  packages/html/stories/Folding.stories.ts
  packages/html/stories/SwimLanes.stories.js
  packages/html/stories/shared/configure.js
  packages/website/docs/usage/migrate-from-mxgraph.md
Labels: bug

#392 feat: let style edge marker fill and stroke colors
  packages/core/src/types.ts
  packages/core/src/view/geometry/edge/ConnectorShape.ts
  packages/html/stories/Markers.stories.ts
Labels: enhancement

#391 docs: improve guidance in PR template
  .github/pull_request_template.md
Labels: documentation

#364 fix: add null check to connection validation message
  packages/core/src/view/handler/ConnectionHandler.ts
  packages/core/src/view/other/Multiplicity.ts
  packages/html/stories/Validation.stories.js
Labels: bug

#394 chore(readme): fix typo in website link
  README.md
Labels: documentation

#395 ci: fix github release template
  .github/workflows/create-github-release.yml
Labels: chore

#396 fix: remove circular dependency in ModelXmlSerializer
  packages/core/src/serialization/ModelXmlSerializer.ts
Labels: bug

#397 chore: declare @maxgraph/core as a module package
  packages/core/package.json
Labels: chore
