Repository maxGraph/maxGraph, pull requests merged in 2024-07, with the labels that each got.

#480 feat!: ease the configuration to rotate the selected vertex
  CHANGELOG.md
  packages/core/src/index.ts
  packages/core/src/view/handler/ConnectionHandler.ts
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/handler/VertexHandler.ts
  packages/core/src/view/handler/config.ts
  packages/html/.storybook/preview.ts
  packages/html/stories/Handles.stories.ts
  packages/html/stories/Stencils.stories.ts
Labels: enhancement

#484 feat: declare the package as side effects free
  packages/core/package.json
Labels: enhancement

#487 docs: improve setup instructions for ts-example
  packages/ts-example/README.md
Labels: documentation

#486 docs: improve setup instructions for js-example
  packages/js-example/README.md
Labels: documentation

#488 fix: correctly encode Geometry XML node when maxGraph is minified
  packages/core/src/serialization/register.ts
Labels: bug
