Repository maxGraph/maxGraph, pull requests merged in 2025-01, with the labels that each got.

#572 fix: popup menu story caused has more submenus open
  packages/html/.storybook/preview.ts
Labels: bug

#609 ci: build and deploy the website when the storybook resources change
  .github/workflows/generate-website.yml
Labels: chore

#610 fix: ensure that codecs for base JS elements are registered
  packages/core/src/serialization/register.ts
Labels: bug

#617 chore(deps-dev): bump vite and test dependencies
  package-lock.json
  packages/core/package.json
  packages/ts-example-without-defaults/package.json
  packages/ts-example/package.json
Labels: dependencies, skip-changelog, javascript

#619 chore(deps-dev): bump docusaurus from 3.6.3 to 3.7.0
  package-lock.json
  packages/website/package.json
Labels: dependencies, skip-changelog, javascript

#621 docs: remove mxGraph resources that are no longer used
  packages/website/docs/tutorials/assets/graphs/method_call_hierarchy.png
  packages/website/docs/tutorials/graph.md
  packages/website/old-mxgraph/css/manual-colors.css
  packages/website/old-mxgraph/css/manual-styles.css
  packages/website/old-mxgraph/images/MX_MANUAL_html_1cc55dd3_loop_connector.png
  packages/website/old-mxgraph/images/MX_MANUAL_html_ba4bf13_mxGraph_console.png
  packages/website/old-mxgraph/images/architecture.png
  packages/website/old-mxgraph/images/logo.jpg
  packages/website/old-mxgraph/images/mx_man_architecture.png
  packages/website/old-mxgraph/images/mx_man_hello_world.png
  packages/website/old-mxgraph/images/mxgraph_logo.gif
  packages/website/old-mxgraph/js/toc.js
  packages/website/old-mxgraph/known-issues.html
  packages/website/old-mxgraph/manual.html
Labels: documentation

#622 docs: reorganize and improve the manual pages
  package-lock.json
  packages/website/docs/manual/assets/model/drill_down_inside.png
  packages/website/docs/manual/assets/model/drill_down_menu.png
  packages/website/docs/manual/assets/model/drill_down_top_level.png
  packages/website/docs/manual/assets/model/group_structure_complex_example.png
  packages/website/docs/manual/assets/model/group_structure_hello-world-example.png
  packages/website/docs/manual/assets/model/layers_example.png
  packages/website/docs/manual/assets/model/layout_overlap.png
  packages/website/docs/manual/assets/model/properties_vertex.png
  packages/website/docs/manual/assets/model/simple_workflow.png
  packages/website/docs/manual/cells.md
  packages/website/docs/manual/group-and-complexity-management.md
  packages/website/docs/manual/index.md
  packages/website/docs/manual/model-and-cells.md
  packages/website/docs/manual/model-and-transactions.md
  packages/website/docs/usage/migrate-from-mxgraph.md
  packages/website/docusaurus.config.ts
  packages/website/package.json
Labels: documentation

#624 docs: integrate contents from the mxGraph Java manual
  packages/website/docs/manual/index.md
  packages/website/old-mxgraph/images/mx_man_stencil_loaded.png
  packages/website/old-mxgraph/manual_javavis.html
Labels: documentation

#620 feat: introduce global config for the Entity Relation connector
  packages/core/src/index.ts
  packages/core/src/util/Constants.ts
  packages/core/src/view/style/config.ts
  packages/core/src/view/style/edge/EntityRelation.ts
  packages/html/.storybook/preview.ts
  packages/html/stories/Folding.stories.ts
  packages/website/docs/usage/global-configuration.md
Labels: enhancement

#626 feat: make the stencils XML schema available in the npm package
  packages/core/package.json
  packages/core/xsd/stencils.xsd
Labels: enhancement

#625 docs: highlight the getting started page
  README.md
  packages/website/docs/assets/getting-started/first-graph.gif
  packages/website/docs/assets/getting-started/vertex-style.png
  packages/website/docs/demo-and-examples.md
  packages/website/docs/getting-started.mdx
  packages/website/docs/intro.md
  packages/website/docusaurus.config.ts
Labels: documentation

#627 docs: fix a broken link in the migrate from mxGraph guide
  packages/website/docs/usage/migrate-from-mxgraph.md
Labels: documentation

#628 chore(deps-dev): bump some lint dependencies
  package-lock.json
  package.json
  packages/core/src/serialization/ModelXmlSerializer.ts
  packages/core/src/view/GraphView.ts
  packages/core/src/view/cell/CellRenderer.ts
  packages/core/src/view/geometry/Shape.ts
  packages/core/src/view/handler/ConstraintHandler.ts
  packages/core/src/view/mixins/CellsMixin.ts
  packages/core/src/view/mixins/TooltipMixin.ts
Labels: dependencies, skip-changelog, javascript

#629 ci: configure dependabot to update JavaScript dependencies
  .github/dependabot.yml
Labels: chore

#635 refactor: migrate the "Animation" story to TypeScript
  packages/html/stories/Animation.stories.ts
Labels: refactor

#633 feat!: make edge bend points easier to manage
  CHANGELOG.md
  packages/core/src/view/handler/EdgeHandler.ts
  packages/core/src/view/handler/EdgeSegmentHandler.ts
  packages/core/src/view/handler/config.ts
  packages/html/stories/CustomHandlesConfiguration.stories.ts
  packages/website/docs/usage/migrate-from-mxgraph.md
Labels: enhancement

#638 refactor: migrate the "AutoLayout" story to TypeScript
  packages/core/src/view/handler/EdgeHandler.ts
  packages/html/stories/AutoLayout.stories.ts
Labels: refactor

#641 docs: update references to GraphDataModel
  packages/core/src/serialization/CodecRegistry.ts
  packages/core/src/util/Constants.ts
  packages/core/src/util/ObjectIdentity.ts
  packages/core/src/util/styleUtils.ts
  packages/core/src/view/event/EventSource.ts
  packages/core/src/view/handler/ConnectionHandler.ts
  packages/core/src/view/image/ImageBox.ts
  packages/core/src/view/undoable_changes/ChildChange.ts
  packages/core/src/view/undoable_changes/CollapseChange.ts
  packages/core/src/view/undoable_changes/GeometryChange.ts
  packages/core/src/view/undoable_changes/RootChange.ts
  packages/core/src/view/undoable_changes/StyleChange.ts
  packages/core/src/view/undoable_changes/TerminalChange.ts
  packages/core/src/view/undoable_changes/ValueChange.ts
  packages/core/src/view/undoable_changes/VisibleChange.ts
Labels: documentation

#642 docs: integrate remaining mxGraph resources
  packages/core/src/Client.ts
  packages/website/docs/development/high-level-api-description.md
  packages/website/old-mxgraph/api-specification.txt
  packages/website/old-mxgraph/images/MX_MANUAL_html_1cc55dd3_loop_connector.png
  packages/website/old-mxgraph/images/MX_MANUAL_html_ba4bf13_mxGraph_console.png
  packages/website/old-mxgraph/images/MX_MANUAL_html_m75de608.png
Labels: documentation

#645 refactor: remove clipboard fallback for old browsers
  packages/core/src/editor/Editor.ts
  packages/core/src/util/Clipboard.ts
  packages/core/src/util/Utils.ts
Labels: refactor

#647 docs: apply minor improvements
  README.md
  packages/website/docs/getting-started.mdx
  packages/website/docs/usage/css-and-images.md
Labels: documentation

#593 ci: improve the template of the GitHub release
  .github/workflows/create-github-release.yml
Labels: chore

#650 chore: add a script to simplify version update on release
  packages/core/package.json
  packages/core/src/Client.ts
  packages/website/docs/development/release.md
  scripts/update-versions.mjs
Labels: chore

#651 ci(release): fix api call to get milestone number
  .github/workflows/create-github-release.yml
Labels: chore

#653 docs: fix typo in CHANGELOG
  CHANGELOG.md
Labels: documentation

#654 docs: apply quick fixes to the "getting started" and "demos" page
  README.md
  packages/website/docs/demo-and-examples.md
  packages/website/docs/getting-started.mdx
Labels: documentation

#655 docs(release): better explain how to choose the new version
  packages/website/docs/development/release.md
Labels: documentation

#656 docs: add more information about perimeters
  packages/core/src/types.ts
  packages/core/src/view/Graph.ts
  packages/core/src/view/GraphView.ts
  packages/core/src/view/cell/CellState.ts
  packages/website/docs/usage/assets/perimeters/perimeter-point-computation-01-context.png
  packages/website/docs/usage/assets/perimeters/perimeter-point-computation-02-center.png
  packages/website/docs/usage/assets/perimeters/perimeter-point-computation-03-orthogonal_projection.png
  packages/website/docs/usage/assets/perimeters/perimeters-diagrams.drawio
  packages/website/docs/usage/assets/perimeters/story-overview.png
  packages/website/docs/usage/perimeters.md
Labels: documentation
